services:
  telegraf:
    image: telegraf:1.32-alpine
    container_name: telegraf
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    ports:
      - '8125:8125/udp'
    networks:
      - telegraf_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  influxdb:
    image: influxdb:1.11-alpine
    container_name: influxdb
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
    networks:
      - telegraf_network

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: brisa-iot-mqtt-broker
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    stdin_open: true 
    tty: true
    networks:
      - telegraf_network

volumes:
  influxdb_data: {}

networks:
  telegraf_network: {}
